version: "3.8"
services:
  broker-adapter:
  build: .
  ports:
    - "8082:8080"
  depends_on:
    - kafka
    - redis
kafka:
  image: wurstmeister/kafka
  ports:
    - "9092:9092"
  environment:
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
redis:
  image: redis
  ports:
    - "6379:6379"
